### PR TITLE
[depends] bump jsoncpp to 1.8.3

### PR DESCRIPTION
**Pull request by Rechi**

### CODE REVIEW

**Comment by fuzzard** [comment]
id be wary of this. 1.x.y branches have deprecated the older reader/writers and implemented new builders that change behaviour. Anyone that builds from source is now going to be spammed with a lot of deprecation warnings.

I'd suggest at this stage to stick to the 0.x.y branch, unless your going to change to the new methods in the codebase.

**Comment by Rechi** [comment]
Have a look at https://packages.qa.debian.org/libj/libjsoncpp.html and https://launchpad.net/ubuntu/+source/libjsoncpp they use 1.7 in all recent versions.
If you don't want the deprecations warnings disable them via `CMAKE_CXX_FLAGS`. Also Travis CI only shows one deprecation warning, Windows shows 7.

**Comment by fuzzard** [comment]
can i suggest you implement the charreaderbuilder then. Below is a patch for it. I dont have time to do a PR to your branch this morning sorry.

From 10c5d24ba7d32cc94c972c9a2791b01a2e761ae0 Mon Sep 17 00:00:00 2001
From: fuzzard <bmurphy@bcmcs.net>
Date: Wed, 15 Nov 2017 05:58:09 +1000
Subject: [PATCH] json::CharReaderBuilder implementation

---
 src/HDHomeRunTuners.cpp | 10 ++++++----
 1 file changed, 6 insertions(+), 4 deletions(-)

diff --git a/src/HDHomeRunTuners.cpp b/src/HDHomeRunTuners.cpp
index 9890ca4..ddedb16 100644
--- a/src/HDHomeRunTuners.cpp
+++ b/src/HDHomeRunTuners.cpp
@@ -47,8 +47,10 @@ unsigned int HDHomeRunTuners::PvrCalculateUniqueId(const String& str)
 bool HDHomeRunTuners::Update(int nMode)
 {
   struct hdhomerun_discover_device_t foundDevices[16];
-  String strUrl, strJson;
-  Json::Reader jsonReader;
+  String strUrl, strJson, jsonReaderError;
+  Json::CharReaderBuilder jsonReaderBuilder;
+  std::unique_ptr<Json::CharReader> const reader(jsonReaderBuilder.newCharReader());
+
   //
   // Discover
   //
@@ -106,7 +108,7 @@ bool HDHomeRunTuners::Update(int nMode)
 
       if (GetFileContents(strUrl.c_str(), strJson))
       {
-        if (jsonReader.parse(strJson, pTuner->Guide) &&
+        if (reader->parse(strJson.c_str(), strJson.c_str() + strJson.size(), &pTuner->Guide, &jsonReaderError) &&
           pTuner->Guide.type() == Json::arrayValue)
         {
           for (auto& tunerGuide : pTuner->Guide)
@@ -185,7 +187,7 @@ bool HDHomeRunTuners::Update(int nMode)
 
       if (GetFileContents(strUrl.c_str(), strJson))
       {
-        if (jsonReader.parse(strJson, pTuner->LineUp) &&
+        if (reader->parse(strJson.c_str(), strJson.c_str() + strJson.size(), &pTuner->LineUp, &jsonReaderError) &&
           pTuner->LineUp.type() == Json::arrayValue)
         {
           std::set<String> guideNumberSet;
-- 
2.6.4

**Comment by Rechi** [comment]
@fuzzard done
Before merging this, jsoncpp has to be bumped in pvr.argustv, otherwise this addon will fail building for nightlies in jenkins.

**Comment by Rechi** [comment]
@FernetMenta just noticed `Json::Reader` already is marked deprecated in the version you have updated to earlier.

**Comment by fuzzard** [comment]
argustv hasnt been building for months. It hasnt been updated to pvr api 5.7.0. I had a brief look about a month ago, but really didnt have the time to work out what it needed to get back up and running, and the maintainer says he no longer has an argustv backend so hasnt really any intention to update it at this point.

just a note regarding the jsoncpp 1.x.y branch, it is considered api incompatible by the maintainer. I had a branch running with 1.8.3 a little while back (hence the quick patch), but i never bothered to fully test everything because of the deprecation warnings (even without deprecated functions being used) on msvc builds. Their are PR's and commits post the 1.8.3 release tag that reduce the deprecations on msvc warnings, but who knows when a new release will be tagged.

**Comment by Rechi** [comment]
argustv doesn't have to build, only jsoncpp version has to be bumped there. Reason, jenkins uses only the dependeny  (grouped by name) from the lowest addon id (pvr.a comes before pvr.h).

**Comment by Rechi** [comment]
Just a note, jenkins already uses jsoncpp 1.8.3 for this binary addon (pvr.argustv was already bumped).

**Comment by fuzzard** [comment]
probably going to need @ksooo to do the merge. Not sure who else has access, and @zcsizmadia  hasnt been around for a couple months.

**Pull request merged**
