### PR TITLE
contentmask and EPG_TAG updates

### PR DESCRIPTION
**Pull request by fuzzard**
Updates some filter content masks. Looking to fill out a few more of the kodi standard ones, but cant find anything further on channels i receive. Will check every now and again for others.

Reordered filters to be alphabetical for the content masks, but can revert that and just add the Kids and Movies filters if desired. Intent is to fill out others if SD provides filters for any currently unused ones.

### CODE REVIEW

**Comment by MatthewLundberg** [comment]
I'm not sure, but the values of these *CONTENTMASK* macros appear to be intended for a bitmask.  If so, it is probably not correct to assign to nGenreType, but |= should be used instead.

Note that "Filter" is a Json array, so the loop body may run more than once.

**Comment by fuzzard** [comment]
Yeah, i believe the original is incorrect in how it handles it. Not really aiming to fix/change it at this time, as i havent looked into how the contentmask is handled by kodi. Obviously the ngenretype just returns the last matched contentmask with the current implementation, what im unsure of is if genre's with mixed content masks actually change colours shown on epg tiles. At a guess you would think it does, but again, havent looked at it at all.

**Comment by fuzzard** [comment]
Having a quick glance at pvr.mediaportal, i dont think SD provide enough filters/genres to worry about doing this right. SD only send out very generic filters, except on movies, and even then its pretty generic from what i can see in my area. 
If your area lists anything more specific, would love to see a log from the guide. Happy to adapt it if i have a reference to work from.

**Comment by fuzzard** [comment]
Pushed another commit to add additional EPG_Tag fields. This gives us episode name. The other just leads to potential in the future as SD keeps track of series with the seriesID. If recording were to be added in the future, would enable serieslink easily.

**Comment by fuzzard** [comment]
Rebased

**Pull request closed without merging**
