### PR TITLE
Epg

### PR DESCRIPTION
**Pull request by phunkyfish**
v4.2.0
- Add EPG storage

### CODE REVIEW

**Comment by phunkyfish** [comment]
@fuzzard any chance you could run time test this?

**Comment by fuzzard** [comment]
As discussed on slack, im not sure theres a great deal of benefit to pvr.hdhomerun with it in its current state.

having said that, @djp952 had mentioned he may (or may not) look at implementing the dvr record engine into this addon. If that was ever done (by anyone really) i could see the benefit to this. Currently SD controlled epg data for non dvr subscribers is 4 (or is it 3?) hours of guide data. We have no recording, and cant use timers days in advance (no guide data)*.

I did once PR something that would allow using xmltv sources for importing guide data, and im sure that would make more use out of this, but i doubt id ever revisit it to be honest.

@djp952 if you have time, i wouldnt mind your viewpoint, as you've expressed at least a little interest about the future features. And you are no doubt across the particulars of SD's current service, for both subscriber and non subscriber. I've only ever been a non dvr user.

edit: * i guess we could implement one shot timers that arent backed by epg data, and are just time/date based. Just never bothered me too much to implement any timer stuff, haha. Once again, i did PR a recording service for this a while back that implemented timers to a certain extent, but again, i doubt i'd revisit it anytime soon. And it would want a major rework i think, quality probably not where real devs may want it, haha.

**Comment by djp952** [comment]
While it was asked of me a few times, I've shied away from local recordings for a few reasons. 

For my addon, the entire thing relies upon SD's DVR service.  Without the DVR service it really doesn't do anything useful.  Being asked by SD to discontinue use of all the JSON-based EPG data and rely only on the XMLTV data I think really put the nail in that idea's coffin on my end as well.  The addon has zero value-add if you're not paying SD. (main reason it would make a terrible mainstream Kodi addon, you must pay for something or it's pointless)

The model SD employs, having the DVR engine running somewhere centralized and then connect as many clients as you want, also made me concerned with how reliable such a thing would be anyway compared to that.  To do local recordings, the PVR would need to either be "always on", or have a mechanism to wake the machine via a timer of some kinda like Media Center used to do.  I'd only know how to make that work well on Windows, and my user base seems to prefer Android (Windows comes in second).  Windows UWP, Linux, macOS, etc are too far out of my wheelhouse.

I also try to be cognizant that SD has been extremely accommodating to my project and I "sell" it as an alternative to their application for folks that prefer Kodi, so it would probably be bad form for me to try to replace their DVR service anyway.

I think a lot of people would probably jump on it if you can make it work well, though.  I agree that having a way to bring in more extensive data for the EPG would be a huge value-add over the 4-hour window you can access now.  One-shot date/time/channel timers would be nice as well, my addon can't do those at all, it's a limitation of the SD backend.

Has any consideration ever been put into a Kodi-based recording solution as opposed to a PVR client solution?  If the functionality were in Kodi itself, the user could have any PVR addon they want installed and Kodi could access it's EPG and live streams via the existing PVR API. Just a random thought :)

Sorry not much actual help, more justification of why I have never done it :)

**Comment by MatthewLundberg** [comment]
I've been working on a replacement for this PVR for some time now.  My fork is at https://github.com/MatthewLundberg/pvr.hdhomerun (see Matrix branch) but it is very far diverged from the original at this point.  It builds on Windows and Linux (Fedora).

Here's the current state of my PVR.

Added functionality:

14 day program guide for subscribers, 24 hours for nonsubscribers, with an option to remove channels by number.  Note that the 4-hour EPG window in the official PVR is due to the way that the data is pulled from SD.  You can get 24 hours for nonsubscribers, but you have to poll each channel individually.

Can use the SD record engine for both live TV and recordings.  When the record engine is used for live TV, one tuner is used for multiple clients receiving the same channel (or one tuner to both record and watch).

If the SD record engine is not used for live TV, there are options to set preferred tuners and blacklist tuners by ID.  This is to help play more nicely with other applications.  (Originally that was WMC but WMC doesn't really matter at this point.)

Opens the connection to the tuner and uses ReadLiveStream/ReadRecordedStream to communicate with Kodi.  As a result, there is not a race condition when selecting a tuner to use.


Missing Features that I would like to implement (also missing from the official PVR):

Can't schedule recordings.  You have to use another application.
Pausing and seeking for live TV does not work.
Pausing and seeking for a recording in progress does not work (does work for completed recordings).
No support for legacy devices.

**Comment by phunkyfish** [comment]
Closing this PR for now ;)

Looks like you have taken this a long way @MatthewLundberg . I have implemented pausing/seek for live TV and in progress recordings in a few addons if you ever want some help/guidance.

**Comment by djp952** [comment]
Not to interject, but also for @MatthewLundberg, check out the new inputstream.ffmpeg addon in Matrix.  It appears to be able to support all of the tricks you'll need to interface with the SD DVR live streams for pause/seek/etc.  You can also still handle the input stream yourself, but use the Kodi file implementation with the "seekable" flag set.  That should work OK too.  Sorry to interject!

**Pull request closed without merging**
